monolog:
    channels: [app]
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: error
        console:
            type: console
            channels: [!app]
